import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";


export default function Home() {
  const router = useRouter();
  // const hello = trpc.post.hello.useQuery({ text: "from tRPC" });
  useEffect(() => {
    let checkUser: any = localStorage.getItem("user") as any;
    if (checkUser !== "true") {
      router.push("/login");
    } else if (checkUser === "true") {
      router.push("/");
    } else {
      console.log("/login", localStorage.getItem("user"));
    }
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]"></main>
    </>
  );
}
